### PR TITLE
STOR-1065: Rename node-driver-registrar RBAC and Rework sidecar bindings to bind common ClusterRoles

### PR DESCRIPTION
**Pull request by mpatlasov**
The first patch in this PR addresses the following issue:

Most of the RBAC seem to be unnecessary. The only important rule there is making the registrar privileged. Perms for "secrets" also required by node-label-updater, because otherwise it complains:
```
{"level":"info","timestamp":"2023-06-23T12:29:33.563Z","caller":"cmd/main.go:66","msg":"Starting controller for adding node labels","watcher-name":"vpc-node-label-updater"}
{"level":"info","timestamp":"2023-06-23T12:29:33.564Z","caller":"cmd/main.go:74","msg":"Getting node details","watcher-name":"vpc-node-label-updater"}
{"level":"info","timestamp":"2023-06-23T12:29:33.587Z","caller":"nodeupdater/utils.go:53","msg":"Fetching secret configuration.","watcher-name":"vpc-node-label-updater"}
{"level":"info","timestamp":"2023-06-23T12:29:33.587Z","caller":"authenticator/authenticator.go:48","msg":"Initializing authenticator","name":"secret-provider","secret-provider-type":"unmanaged-secret-provider"}
{"level":"warn","timestamp":"2023-06-23T12:29:33.589Z","caller":"authenticator/authenticator.go:86","msg":"Unable to fetch ibm-cloud-credentials","name":"secret-provider","secret-provider-type":"unmanaged-secret-provider","error":"secrets \"ibm-cloud-credentials\" is forbidden: User \"system:serviceaccount:openshift-cluster-csi-drivers:ibm-vpc-block-node-sa\" cannot get resource \"secrets\" in API group \"\" in the namespace \"openshift-cluster-csi-drivers\"","key-name":"ibm-credentials.env"}
{"level":"error","timestamp":"2023-06-23T12:29:33.591Z","caller":"authenticator/authenticator.go:89","msg":"Error initializing authenticator","name":"secret-provider","secret-provider-type":"unmanaged-secret-provider","error":"secrets \"storage-secret-store\" is forbidden: User \"system:serviceaccount:openshift-cluster-csi-drivers:ibm-vpc-block-node-sa\" cannot get resource \"secrets\" in API group \"\" in the namespace \"openshift-cluster-csi-drivers\""}
{"level":"error","timestamp":"2023-06-23T12:29:33.591Z","caller":"secret_provider/unmanaged_secret_provider.go:65","msg":"Error initializing unmanaged secret provider","name":"secret-provider","secret-provider-type":"unmanaged-secret-provider","error":"secrets \"storage-secret-store\" is forbidden: User \"system:serviceaccount:openshift-cluster-csi-drivers:ibm-vpc-block-node-sa\" cannot get resource \"secrets\" in API group \"\" in the namespace \"openshift-cluster-csi-drivers\""}
{"level":"error","timestamp":"2023-06-23T12:29:33.591Z","caller":"nodeupdater/utils.go:59","msg":"Error initializing secret provider","watcher-name":"vpc-node-label-updater","error":"secrets \"storage-secret-store\" is forbidden: User \"system:serviceaccount:openshift-cluster-csi-drivers:ibm-vpc-block-node-sa\" cannot get resource \"secrets\" in API group \"\" in the namespace \"openshift-cluster-csi-drivers\""}
{"level":"fatal","timestamp":"2023-06-23T12:29:33.591Z","caller":"cmd/main.go:98","msg":"Failed to read secret configuration","watcher-name":"vpc-node-label-updater","error":"secrets \"storage-secret-store\" is forbidden: User \"system:serviceaccount:openshift-cluster-csi-drivers:ibm-vpc-block-node-sa\" cannot get resource \"secrets\" in API group \"\" in the namespace \"openshift-cluster-csi-drivers\""}
```

The second patch in PR rework sidecar bindings to bind common ClusterRoles:

PR https://github.com/openshift/cluster-storage-operator/pull/379 published builiding blocks of sidecar ClusterRoles. Now, ibm-vpc-block csi driver operator may compose its sidecars ClusterRoles from those building blocks.

The patch also moves permissions for `leases` resource from ClusterRole to per-namespace Role (`assets/rbac/lease_leader_election_role.yaml`).

### CODE REVIEW

**Comment by mpatlasov** [comment]
/hold

For some reasons the operator doesn't see roles published by CSO:
```
level=error msg=Cluster operator storage Degraded is True with IBMVPCBlockCSIDriverOperatorCR_IBMBlockDriverStaticResourcesController_SyncError: IBMVPCBlockCSIDriverOperatorCRDegraded: IBMBlockDriverStaticResourcesControllerDegraded: "rbac/main_attacher_binding.yaml" (string): clusterroles.rbac.authorization.k8s.io "openshift-csi-main-attacher-role" not found
```

**Comment by mpatlasov** [comment]
The cluster installation went smoothly for release image `registry.build05.ci.openshift.org/ci-ln-k318ftk/release:latest` built by cluster-bot on top of https://github.com/openshift/cluster-storage-operator/pull/386 and https://github.com/openshift/ibm-vpc-block-csi-driver-operator/pull/64

CVO published cluster roles 5 mins before operator started:
```
$ oc get clusterrole ibm-vpc-node-label-updater-role
NAME                              CREATED AT
ibm-vpc-node-label-updater-role   2023-07-18T21:22:21Z

$ oc get clusterrole openshift-csi-main-provisioner-role
NAME                                  CREATED AT
openshift-csi-main-provisioner-role   2023-07-18T21:14:57Z
```

No messages like `clusterrole "openshift-csi-main-resizer-role" not found` at all:

```
$ oc logs ibm-vpc-block-csi-driver-operator-68448b9485-ln6cx -n openshift-cluster-csi-drivers |grep main
I0718 21:22:20.202487       1 event.go:298] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-cluster-csi-drivers", Name:"ibm-vpc-block-csi-driver-operator", UID:"8ea66f2b-eb75-4207-ac6e-660aaa21f9a0", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'ClusterRoleBindingCreated' Created ClusterRoleBinding.rbac.authorization.k8s.io/vpc-block-main-attacher-binding because it was missing
I0718 21:22:20.323280       1 event.go:298] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-cluster-csi-drivers", Name:"ibm-vpc-block-csi-driver-operator", UID:"8ea66f2b-eb75-4207-ac6e-660aaa21f9a0", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'ClusterRoleBindingCreated' Created ClusterRoleBinding.rbac.authorization.k8s.io/vpc-block-main-provisioner-binding because it was missing
I0718 21:22:22.145844       1 event.go:298] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-cluster-csi-drivers", Name:"ibm-vpc-block-csi-driver-operator", UID:"8ea66f2b-eb75-4207-ac6e-660aaa21f9a0", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'ClusterRoleBindingCreated' Created ClusterRoleBinding.rbac.authorization.k8s.io/vpc-block-main-resizer-binding because it was missing
I0718 21:22:23.314148       1 event.go:298] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-cluster-csi-drivers", Name:"ibm-vpc-block-csi-driver-operator", UID:"8ea66f2b-eb75-4207-ac6e-660aaa21f9a0", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'ClusterRoleBindingCreated' Created ClusterRoleBinding.rbac.authorization.k8s.io/vpc-block-main-snapshotter-binding because it was missing
```

I'll `unhold` this PR as soon as https://github.com/openshift/cluster-storage-operator/pull/386 merged.

**Comment by ropatil010** [comment]
/label qe-approved
Results added here: [STOR-1363](https://issues.redhat.com/browse/STOR-1363#:~:text=Red%20Hat%20Employee-,Platform%3A%20IBM,-Payload%3A%204.14.0%2D0)

**Pull request merged**
