### PR TITLE
OCPBUGS-42231: Reorder static resources to create RBAC first

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/OCPBUGS-42231
/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
/payload-job pull-ci-openshift-installer-master-e2e-ibmcloud-ovn

**Comment by dobsonj** [comment]
Hmm, maybe I can't run that job directly from this PR, but we can also check e2e-ibmcloud-csi for `Error creating: pods \"ibm-vpc-block-csi-node-\" is forbidden` in events.json

I can see that event [here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_ibm-vpc-block-csi-driver-operator/125/pull-ci-openshift-ibm-vpc-block-csi-driver-operator-master-e2e-ibmcloud-csi/1813990718058795008/artifacts/e2e-ibmcloud-csi/gather-extra/artifacts/events.json) in e2e-ibmcloud-csi for example, we just don't have the test case that fails in the presubmit job.

**Comment by gnufied** [comment]
So looks like ibmcloud-csi jobs are still permafailing. :( 

/lgtm

**Pull request merged**
