### PR TITLE
STOR-1487: Provide BYOK encryption support for OpenShift on IBM Cloud VPC

### PR DESCRIPTION
**Pull request by dobsonj**
This PR bumps the api version to get the new field, and adds a storageclass hook to add parameters when `EncryptionKeyCRN` is set.

- [STOR-1487](https://issues.redhat.com//browse/STOR-1487): bump openshift/api to get IBMCloudCSIDriverConfigSpec
- [STOR-1487](https://issues.redhat.com//browse/STOR-1487): Provide BYOK encryption support for OpenShift on IBM Cloud VPC

API PR: https://github.com/openshift/api/pull/1649

See also: https://issues.redhat.com/browse/STOR-1357

/cc @openshift/storage @jeffnowicki @cjschaef @phaow

### CODE REVIEW

**Comment by dobsonj** [comment]
I did some simple manual tests. This PR also requires https://github.com/openshift/cluster-storage-operator/pull/423 to update the ClusterCSIDriver CRD.

clusterbot: `build 4.15,openshift/ibm-vpc-block-csi-driver-operator#93,openshift/cluster-storage-operator#423`

Follow the instructions here to create a root key and IAM role:
https://cloud.ibm.com/docs/containers?topic=containers-vpc-block#vpc-block-encryption

Check default settings on the cluster:
```
$ oc get clustercsidriver vpc.block.csi.ibm.io -o json | jq .spec.driverConfig
{
  "driverType": ""
}

$ oc get sc ibmc-vpc-block-10iops-tier -o json | jq .parameters
{
  "csi.storage.k8s.io/fstype": "ext4",
  "encrypted": "false",
  "encryptionKey": "",
  "profile": "10iops-tier",
  "region": "",
  "resourceGroup": "",
  "tags": "",
  "zone": ""
}
```

Setting the driverConfig in the ClusterCSIDriver shows the change reflected in the default StorageClass, pod and PVC provision successfully using customer managed key.
```
$ oc edit clustercsidriver vpc.block.csi.ibm.io
clustercsidriver.operator.openshift.io/vpc.block.csi.ibm.io edited

$ oc get clustercsidriver vpc.block.csi.ibm.io -o json | jq .spec.driverConfig
{
  "driverType": "IBMCloud",
  "ibmcloud": {
    "encryptionKeyCRN": "crn:v1:bluemix:public:kms:us-south:a/18240e5ed3f647cb96ca52dc92d9addd:1f9b7531-6cb5-4a71-9cd9-39666b79b34f:key:c3127d0e-0b18-4a35-ab60-e2507d540e8d"
  }
}

$ oc get sc ibmc-vpc-block-10iops-tier -o json | jq .parameters
{
  "csi.storage.k8s.io/fstype": "ext4",
  "encrypted": "true",
  "encryptionKey": "crn:v1:bluemix:public:kms:us-south:a/18240e5ed3f647cb96ca52dc92d9addd:1f9b7531-6cb5-4a71-9cd9-39666b79b34f:key:c3127d0e-0b18-4a35-ab60-e2507d540e8d",
  "profile": "10iops-tier",
  "region": "",
  "resourceGroup": "",
  "tags": "",
  "zone": ""
}
```

Removing the config spec from the ClusterCSIDriver reverts the StorageClass, pod and PVC provision successfully using platform managed key.
```
$ oc edit clustercsidriver vpc.block.csi.ibm.io
clustercsidriver.operator.openshift.io/vpc.block.csi.ibm.io edited

$ oc get clustercsidriver vpc.block.csi.ibm.io -o json | jq .spec.driverConfig
{
  "driverType": ""
}

$ oc get sc ibmc-vpc-block-10iops-tier -o json | jq .parameters
{
  "csi.storage.k8s.io/fstype": "ext4",
  "encrypted": "false",
  "encryptionKey": "",
  "profile": "10iops-tier",
  "region": "",
  "resourceGroup": "",
  "tags": "",
  "zone": ""
}
```

**Comment by Phaow** [comment]
Hello @dobsonj , I test with the pre merged build `clusterbot: build 4.15,openshift/ibm-vpc-block-csi-driver-operator#93,openshift/cluster-storage-operator#423`, all the inject `encryptionKey` logic looks good, just wonder that could we do some enhancement for the `getEncryptionKeyHook ` logs, I could see too many duplicated logs especially when the key is injected, from my understanding the inject used key should only print 1 time if we don't change the key. Since it is debug level logs, so maybe there's low risk.
```console
[pewang@preserve-storage-server1 ~]$ oc logs ibm-vpc-block-csi-driver-operator-67d95dd5df-htgfh | grep  'No IBMCloudCSIDriverConfigSpec'|wc -l
108
[pewang@preserve-storage-server1 ~]$ oc logs ibm-vpc-block-csi-driver-operator-67d95dd5df-htgfh | grep  'Setting encryptionKey = crn:v1:bluemix:public:kms:eu-gb:a/fdc2e14cf8bc4d53a67f972dc2e2c861:70691649-8640-41c5-9af8-68ebbdd8c660:key:ed70d7a5-bec8-47cd-8a05-ef224226432c in StorageClass ibmc-vpc-block-custom'| wc -l
130
```

In addition , I found that seems the vpc block csi driver doesn't work well with the specified `encryptionKey`, after the key injected to the managed storage classes, the managed storage classes couldn't provision encryption volume succeed. Do you try provision volume with the managed storage classes injected encryptionKey on your local test? Not sure I missed something here.
```console
[pewang@preserve-storage-server1 ~]$ oc logs ibm-vpc-block-csi-controller-748c9c5946-8kdns -c csi-provisioner| grep 'pvc-encryption'
I1128 10:37:15.863361       1 controller.go:1366] provision "default/pvc-encryption" class "ibmc-vpc-block-10iops-tier": started
I1128 10:37:15.863632       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"pvc-encryption", UID:"f42fcb6b-7efd-44a7-9e9e-1155d9978a8d", APIVersion:"v1", ResourceVersion:"90625", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/pvc-encryption"
I1128 10:47:15.864255       1 controller.go:1366] provision "default/pvc-encryption" class "ibmc-vpc-block-10iops-tier": started
I1128 10:47:15.864357       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"pvc-encryption", UID:"f42fcb6b-7efd-44a7-9e9e-1155d9978a8d", APIVersion:"v1", ResourceVersion:"90625", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "ibmc-vpc-block-10iops-tier": rpc error: code = DeadlineExceeded desc = context deadline exceeded
I1128 10:47:15.864505       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"pvc-encryption", UID:"f42fcb6b-7efd-44a7-9e9e-1155d9978a8d", APIVersion:"v1", ResourceVersion:"90625", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/pvc-encryption"
I1128 10:47:15.904046       1 round_trippers.go:553] PATCH https://172.30.0.1:443/api/v1/namespaces/default/events/pvc-encryption.179bc3222ff6b6c0 200 OK in 14 milliseconds
I1128 10:57:15.865329       1 controller.go:1366] provision "default/pvc-encryption" class "ibmc-vpc-block-10iops-tier": started
I1128 10:57:15.865837       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"pvc-encryption", UID:"f42fcb6b-7efd-44a7-9e9e-1155d9978a8d", APIVersion:"v1", ResourceVersion:"90625", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "ibmc-vpc-block-10iops-tier": rpc error: code = DeadlineExceeded desc = context deadline exceeded
I1128 10:57:15.865987       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"pvc-encryption", UID:"f42fcb6b-7efd-44a7-9e9e-1155d9978a8d", APIVersion:"v1", ResourceVersion:"90625", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/pvc-encryption"
I1128 10:57:15.892307       1 round_trippers.go:553] PATCH https://172.30.0.1:443/api/v1/namespaces/default/events/pvc-encryption.179bc3ade2ca528e 200 OK in 26 milliseconds
I1128 10:57:15.907917       1 round_trippers.go:553] PATCH https://172.30.0.1:443/api/v1/namespaces/default/events/pvc-encryption.179bc3222ff6b6c0 200 OK in 15 milliseconds
```

**Comment by dobsonj** [comment]
> /label docs-approved

label didn't take, ETRYAGAIN
/label docs-approved

**Comment by Phaow** [comment]
/label qe-approved
The duplicated debug logs level bug, I'll file a bug track, others all looks good.

**Pull request merged**
