### PR TITLE
STOR-947: support disabling default StorageClass via ClusterCSIDriver

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-947
Marking this WIP until openshift/library-go#1441 merges.
/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
/retitle STOR-947: support disabling default StorageClass via ClusterCSIDriver

**Comment by ropatil010** [comment]
Payload: 4.13.0-0.ci.test-2023-01-25-044031-ci-ln-8xksz7k-latest
Test Results: Working as expected.

Scenarios: Attached [here](https://issues.redhat.com/browse/STOR-922#:~:text=Thank%20Jonathan%20Dobson%20for%20clearing%20doubts.%0AWorking%20as%20expected.%20Tested%20on%20AWS/GCP%20platforms.%C2%A0%C2%A0)

###################test0_Default started #################
oc get clustercsidriver vpc.block.csi.ibm.io -o yaml | grep 'storageClassState'
oc get sc
NAME                                   PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   60m
ibmc-vpc-block-5iops-tier              vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   60m
ibmc-vpc-block-custom                  vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   60m

 change ibmc-vpc-block-5iops-tier volumeBindingMode
 change ibmc-vpc-block-5iops-tier reclaimPolicy
 change ibmc-vpc-block-10iops-tier volumeBindingMode
 change ibmc-vpc-block-10iops-tier reclaimPolicy
 change ibmc-vpc-block-custom volumeBindingMode
 change ibmc-vpc-block-custom reclaimPolicy

 Bydefault test change ibmc-vpc-block-5iops-tier allowVolumeExpansion to false
storageclass.storage.k8s.io/ibmc-vpc-block-5iops-tier patched
 Bydefault result oc get sc ibmc-vpc-block-5iops-tier
NAME     PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-5iops-tier   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   61m

 Bydefault test change ibmc-vpc-block-10iops-tier allowVolumeExpansion to false
storageclass.storage.k8s.io/ibmc-vpc-block-10iops-tier patched
 Bydefault result oc get sc ibmc-vpc-block-10iops-tier
NAME    PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   61m

 Bydefault test change ibmc-vpc-block-custom allowVolumeExpansion to false
storageclass.storage.k8s.io/ibmc-vpc-block-custom patched
 Bydefault result oc get sc ibmc-vpc-block-custom
NAME     PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-custom   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   61m

oc get sc
NAME      PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   61m
ibmc-vpc-block-5iops-tier              vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   61m
ibmc-vpc-block-custom                  vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   61m

oc delete sc
storageclass.storage.k8s.io "ibmc-vpc-block-10iops-tier" deleted
storageclass.storage.k8s.io "ibmc-vpc-block-5iops-tier" deleted
storageclass.storage.k8s.io "ibmc-vpc-block-custom" deleted

oc get sc
NAME                                   PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete    WaitForFirstConsumer   true                  4s
ibmc-vpc-block-5iops-tier              vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   3s
ibmc-vpc-block-custom                  vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   2s
###################test1_Removed started #################
oc get clustercsidriver vpc.block.csi.ibm.io -o yaml | grep 'storageClassState'
  storageClassState: Removed

 Removed test change ibmc-vpc-block-5iops-tier allowVolumeExpansion to false
 Removed test change ibmc-vpc-block-10iops-tier allowVolumeExpansion to false
 Removed test change ibmc-vpc-block-custom allowVolumeExpansion to false
 Removed result oc get sc
No resources found
###################test2_Managed started #################
oc get clustercsidriver vpc.block.csi.ibm.io -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc
NAME                                   PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   35s
ibmc-vpc-block-5iops-tier              vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   35s
ibmc-vpc-block-custom                  vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   35s

 change ibmc-vpc-block-5iops-tier volumeBindingMode
 change ibmc-vpc-block-5iops-tier reclaimPolicy
 change ibmc-vpc-block-10iops-tier volumeBindingMode
 change ibmc-vpc-block-10iops-tier reclaimPolicy
 change ibmc-vpc-block-custom volumeBindingMode
 change ibmc-vpc-block-custom reclaimPolicy

 Managed test change ibmc-vpc-block-5iops-tier allowVolumeExpansion to false
storageclass.storage.k8s.io/ibmc-vpc-block-5iops-tier patched

 Managed result oc get sc ibmc-vpc-block-5iops-tier
NAME                        PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-5iops-tier   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   44s

 Managed test change ibmc-vpc-block-10iops-tier allowVolumeExpansion to false
storageclass.storage.k8s.io/ibmc-vpc-block-10iops-tier patched

 Managed result oc get sc ibmc-vpc-block-10iops-tier
NAME                                   PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   46s

 Managed test change ibmc-vpc-block-custom allowVolumeExpansion to false
storageclass.storage.k8s.io/ibmc-vpc-block-custom patched

 Managed result oc get sc ibmc-vpc-block-custom
NAME                    PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-custom   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   48s

oc get sc
NAME                                   PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true             49s
ibmc-vpc-block-5iops-tier              vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   49s
ibmc-vpc-block-custom                  vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   49s

oc delete sc
storageclass.storage.k8s.io "ibmc-vpc-block-10iops-tier" deleted
storageclass.storage.k8s.io "ibmc-vpc-block-5iops-tier" deleted
storageclass.storage.k8s.io "ibmc-vpc-block-custom" deleted

oc get sc
NAME                                   PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true             3s
ibmc-vpc-block-5iops-tier              vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   2s
ibmc-vpc-block-custom                  vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   1s
###################test3_Unmanaged started #################
oc get clustercsidriver vpc.block.csi.ibm.io -o yaml | grep 'storageClassState'
  storageClassState: Unmanaged

oc get sc
NAME                                   PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   3m2s
ibmc-vpc-block-5iops-tier              vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   3m1s
ibmc-vpc-block-custom                  vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   3m

 change ibmc-vpc-block-5iops-tier volumeBindingMode
 change ibmc-vpc-block-5iops-tier reclaimPolicy
 change ibmc-vpc-block-10iops-tier volumeBindingMode
 change ibmc-vpc-block-10iops-tier reclaimPolicy
 change ibmc-vpc-block-custom volumeBindingMode
 change ibmc-vpc-block-custom reclaimPolicy

 Unmanaged test change ibmc-vpc-block-5iops-tier allowVolumeExpansion to false
storageclass.storage.k8s.io/ibmc-vpc-block-5iops-tier patched

 Unmanaged result oc get sc ibmc-vpc-block-5iops-tier
NAME                        PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-5iops-tier   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   false                  3m10s

 Unmanaged test change ibmc-vpc-block-10iops-tier allowVolumeExpansion to false
storageclass.storage.k8s.io/ibmc-vpc-block-10iops-tier patched

 Unmanaged result oc get sc ibmc-vpc-block-10iops-tier
NAME                                   PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   false                  3m13s

 Unmanaged test change ibmc-vpc-block-custom allowVolumeExpansion to false
storageclass.storage.k8s.io/ibmc-vpc-block-custom patched

 Unmanaged result oc get sc ibmc-vpc-block-custom
NAME                    PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-custom   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   false                  3m14s

oc get sc
NAME                                   PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   false                  3m16s
ibmc-vpc-block-5iops-tier              vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   false                  3m15s
ibmc-vpc-block-custom                  vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   false                  3m14s

oc delete sc
storageclass.storage.k8s.io "ibmc-vpc-block-10iops-tier" deleted
storageclass.storage.k8s.io "ibmc-vpc-block-5iops-tier" deleted
storageclass.storage.k8s.io "ibmc-vpc-block-custom" deleted

oc get sc
No resources found
###################test4a_Multiple default sc Managed started #################
oc get clustercsidriver vpc.block.csi.ibm.io -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc
NAME                                   PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   4m51s
ibmc-vpc-block-5iops-tier              vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   4m51s
ibmc-vpc-block-custom                  vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   4m51s
Creating sc
storageclass.storage.k8s.io/testsc created
Applying patch to sc testsc for changing to default
storageclass.storage.k8s.io/testsc patched

oc get sc
NAME                                   PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   4m55s
ibmc-vpc-block-5iops-tier              vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   4m55s
ibmc-vpc-block-custom                  vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   4m55s
testsc (default)                       vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   3s
###################test4b_Removed started #################
oc get clustercsidriver vpc.block.csi.ibm.io -o yaml | grep 'storageClassState'
  storageClassState: Removed

oc get sc and check ibmc-vpc-block-5iops-tier, ibmc-vpc-block-custom, ibmc-vpc-block-10iops-tier should not be there and testsc should be there
NAME               PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
testsc (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   3m54s
###################test4c_Managed sc started #################
oc get clustercsidriver vpc.block.csi.ibm.io -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc all should be present now ibmc-vpc-block-10iops-tier, ibmc-vpc-block-5iops-tier, testsc
NAME                         PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   2m52s
ibmc-vpc-block-5iops-tier    vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   2m52s
ibmc-vpc-block-custom        vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   2m52s
testsc (default)             vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   8m36s
Deleting all sc
storageclass.storage.k8s.io "testsc" deleted
storageclass.storage.k8s.io "ibmc-vpc-block-10iops-tier" deleted
storageclass.storage.k8s.io "ibmc-vpc-block-5iops-tier" deleted
storageclass.storage.k8s.io "ibmc-vpc-block-custom" deleted

oc get sc ibmc-vpc-block-5iops-tier and ibmc-vpc-block-10iops-tier should be back to default
NAME                                   PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   4s
ibmc-vpc-block-5iops-tier              vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   3s
ibmc-vpc-block-custom                  vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   1s
###################test5a_Managed default sc started #################
oc get clustercsidriver vpc.block.csi.ibm.io -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc
NAME                                   PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   8m12s
ibmc-vpc-block-5iops-tier              vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   8m11s
ibmc-vpc-block-custom                  vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   8m9s
###################test5b_Unmanaged default sc started #################
oc get clustercsidriver vpc.block.csi.ibm.io -o yaml | grep 'storageClassState'
  storageClassState: Unmanaged

oc get sc
NAME                         PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   11m
ibmc-vpc-block-5iops-tier    vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   11m
ibmc-vpc-block-custom        vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   11m
Creating sc
storageclass.storage.k8s.io/testsc created
Applying patch to sc testsc for changing to default
storageclass.storage.k8s.io/testsc patched
Applying patch to sc ibmc-vpc-block-10iops-tier for changing to non default
storageclass.storage.k8s.io/ibmc-vpc-block-10iops-tier patched
oc get sc
NAME                         PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   11m
ibmc-vpc-block-5iops-tier    vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   11m
ibmc-vpc-block-custom        vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   11m
testsc (default)             vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   3s
###################test5c_Removed sc started #################
oc get clustercsidriver vpc.block.csi.ibm.io -o yaml | grep 'storageClassState'
  storageClassState: Removed

oc get sc ibmc-vpc-block-5iops-tier, ibmc-vpc-block-custom, ibmc-vpc-block-10iops-tier should not be there testsc should be there
NAME      PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
testsc (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   5m36s
Deleting sc testsc
storageclass.storage.k8s.io "testsc" deleted

**Comment by dobsonj** [comment]
> /docs-approved

/label docs-approved

**Pull request merged**
